### ISSUE TITLE
Release for 7.4 fix

### ISSUE THREAD

**Issue by benjamindoe** [zetacomponents/Url#4]
Hi,

I've noticed on master there is a fix for the curly brace deprecation. I also noticed there's no release tag for it. Is that commit stable? Could we get a point release for it?

**Comment by derickr** [comment]
That should be in the 1.3.1, which is available on packagist: https://packagist.org/packages/zetacomponents/url

**Comment by benjamindoe** [comment]
Odd, we were still getting that curly brace thing when we upgraded to 1.3.1. If that's the case it might be something I did so I'll close
